POST http://localhost:8080/events/1/register
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q1NkBleGFtcGxlLmNvbSIsImV4cCI6MTczNDU0NjIxNiwidXNlcklkIjoyfQ.vOcjnnts8-9tuTfMGluSA9vMZBdXcBTQlT3S5Bpmhr0